config/routes.rb
PicHack3rMe::Application.routes.draw do
  get '/about' => 'static#about'
  resources :pictures, :only => [:index, :show, :new, :create]
  root :to => 'pictures#new'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  require 'digest/md5'

  has_attached_file :photo, :styles => { :thumbnail => "150x150>" },
                    :url  => "/assets/data/:class/:id_partition/:style/:basename/picture.:extension",
                    :path => ":rails_root/public/assets/data/:class/:id_partition/:style/:basename/picture.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  attr_accessible :photo
  before_post_process :image?
  def image?
    !(photo_content_type =~ /^image.*/).nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PicHack3rMe
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .well
        .center
          %h1= link_to "picHack3r", root_path
          %small
            = link_to 'About', '/about'
            \|
            = link_to 'Gallery', pictures_path
        - if notice
          %div{:class=>"alert alert-success"}= notice
        = yield

app/views/pictures/_form.html.haml
.center
  %h3 Upload a new picture
  %br/
  = form_for @picture do |f|
    -if @picture.errors.any?
      %div{:class=>"alert alert-error"}
        %h2= "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
        %ul
          - @picture.errors.full_messages.each do |msg|
            %li= msg
    = f.file_field :photo
    .actions{:style=>"margin-top:10px"}
      = f.submit 'Upload', :class=>"btn btn-primary btn-large"
      = link_to 'Back', pictures_path, :class=>"btn btn-large" if request.path != '/'

app/views/pictures/edit.html.haml
%h1 Editing picture

= render 'form'

= link_to 'Show', @picture
\|
= link_to 'Back', pictures_path

app/views/pictures/index.html.haml
.center
  %h3 Uploaded images
  %br/
%div.pic_container
  - @pictures.each do |picture|
    %div.picture
      = link_to image_tag(picture.photo.url(:thumbnail)), picture

%br
.center
  = link_to 'New Picture', new_picture_path, :class=>"btn btn-primary btn-large"

app/views/pictures/new.html.haml
= render 'form'

app/views/pictures/show.html.haml
%center
  = link_to 'Back', pictures_path, :class=>"btn btn-large"
%div.image= image_tag @picture.photo.url